model_names: [ax_01_bearing_box, ax_01b_bearing_box, ax_02_bearing, ax_03_axis, ax_04_shaft_nut, ax_05_distance_tube,
              ax_06_cover_plate_defect, ax_06b_cover_plate_no_hole, ax_07_cover_plate_machined, ax_09_motor_with_gearbox,
              ax_10_screw1_coverplate_motor, ax_11_screw2_coverplate_motor, em_01_aid_tray, em_01b_aid_tray_inlay,
              em_02_coverplates_box, er_02_container]

number_of_objects_to_spawn: 18

object_1:
  model_name: 'em_01_aid_tray'
  parent_link: 'platform_5'
  position: [1.3,0.57,0.1]
  orientation: [0,0,1.57]

object_2:
  model_name: 'em_02_coverplates_box'
  parent_link: 'platform_8'
  position: [1.4,-4.88,0.1]
  orientation: [0,0,3.14]

object_3:
  model_name: 'ax_06b_cover_plate_no_hole'
  parent_link: 'platform_8'
  position: [1.25,-4.93,0.1]
  orientation: [0,0,0]

object_4:
  model_name: 'ax_06_cover_plate_defect'
  parent_link: 'platform_8'
  position: [1.25,-5.03,0.1]
  orientation: [0,0,0]

object_5:
  model_name: 'ax_06b_cover_plate_no_hole'
  parent_link: 'conveyor_belt'
  position: [0.06,-4.56,0.11]
  orientation: [0,0,0]

object_6:
  model_name: 'ax_06_cover_plate_defect'
  parent_link: 'conveyor_belt'
  position: [0.31,-4.56 ,0.11]
  orientation: [0,0,0]

object_7:
  model_name: 'ax_01_bearing_box'
  parent_link: 'shelf_4'
  position: [-0.09, -3.9,0.1]
  orientation: [0,0,0]

object_8:
  model_name: 'ax_03_axis'
  parent_link: 'shelf_4'
  position: [-0.1,-3.6,0.127]
  orientation: [0,0,0]

object_9:
  model_name: 'ax_09_motor_with_gearbox'
  parent_link: 'shelf_4'
  position: [-0.1,-3.4,0.1]
  orientation: [0,0,0]

object_10:
  model_name: 'ax_02_bearing'
  parent_link: 'shelf_3'
  position: [-0.025,-3.06,0.1]
  orientation: [0,-1.57,0]

object_11:
  model_name: 'ax_02_bearing'
  parent_link: 'shelf_3'
  position: [-0.025,-2.90,0.1]
  orientation: [0,-1.57,0]

object_12:
  model_name: 'ax_02_bearing'
  parent_link: 'shelf_3'
  position: [-0.025, -2.70,0.1]
  orientation: [0,-1.57,0]

object_13:
  model_name: 'em_02_coverplates_box'
  parent_link: 'shelf_3'
  position: [-0.05,-2.5,0.1]
  orientation: [0,0,1.57]

object_14:
  model_name: 'ax_04_shaft_nut'
  parent_link: 'shelf_2'
  position: [-0.025,-2.15,0.1]
  orientation: [0,-1.57,0]

object_15:
  model_name: 'er_02_container'
  parent_link: 'shelf_2'
  position: [-0.025,-2.0,0.1]
  orientation: [0,0,0]

object_16:
  model_name: 'ax_05_distance_tube'
  parent_link: 'shelf_2'
  position: [-0.025,-1.7,0.1]
  orientation: [0,0,0]

object_17:
  model_name: 'er_02_container'
  parent_link: 'shelf_1'
  position: [-0.025,-1.3,0.1]
  orientation: [0,0,0]

object_18:
  model_name: 'em_01_aid_tray'
  parent_link: 'shelf_1'
  position: [-0.05,-0.9,0.1]
  orientation: [0,0,3.14]